// 効いてなさそう
import 'highlight.js/styles/github-dark-dimmed.css'

import Head from 'next/head'
import router from 'next/router'
import { ChangeEvent, useState } from 'react'

import { usePage } from '@/hooks'

import { Editor } from '@/components/uis/Editor'
import { EmojiPicker } from '@/components/uis/EmojiPicker'
import { IconButton } from '@/components/uis/Icon/IconButton/IconButton'
import { Tooltip } from '@/components/uis/Tooltip'

// import { useRouter } from 'next/router'
// import { useEffect } from 'react'

// import { PageRepository } from '@/repository/db/page/page.repository'

type QueryType = {
  pageId: string
}

// const pageRepo = new PageRepository()

export default function PageDetail() {
  // TODO: You should only use "next/router" on the client side of your app.
  const { pageId } = router.query as QueryType

  const { pages, updatePage } = usePage()
  console.log(pages)

  const page = pages?.find((p) => p.id === pageId)
  console.log(page)
  // const router = useRouter()

  // useEffect(() => {
  //   // if (router.isReady) console.log('PageDetail', pageRepo.get(pageId))
  // }, [pageId, router])

  const handleUpdateEmoji = (emoji: string) => {
    updatePage(pageId, { emoji })
  }

  // TODO: bounceしないと
  const handleUpdateTitle = (e: ChangeEvent<HTMLInputElement>) => {
    updatePage(pageId, { title: e.target.value })
  }

  const [emojiOpen, setEmojiOpen] = useState(false)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div className="sticky top-0 bg-slate-900 z-floating -mt-4 pt-4">
          <div className="flex justify-between items-center">
            <span className="text-sm">🎉 イベント / 🛩️ イタリア旅行</span>
            <Tooltip position="bottom-left" component="シェアする">
              <IconButton icon="twitter" size="md" />
            </Tooltip>
          </div>

          <div className="px-2 py-4">
            <div className="flex items-center gap-1 text-3xl mb-2">
              <EmojiPicker
                isOpen={emojiOpen}
                onOpen={() => {
                  console.log('clicec')
                  setEmojiOpen(true)
                }}
                onClose={() => setEmojiOpen(false)}
                onSelect={handleUpdateEmoji}
              >
                <button className="w-11 h-11 text-3xl p-1 hover:bg-white hover:bg-opacity-10 rounded-md">
                  {page?.emoji}
                </button>
              </EmojiPicker>
              <input
                value={page?.title}
                placeholder="Untitle"
                onChange={handleUpdateTitle}
                className="w-full bg-transparent font-extrabold  outline-none"
              />
            </div>
            <div className="text-xs text-slate-300 flex gap-4">
              <div>
                <span>作成日時 2023/02/28 04:10</span>
              </div>
              <div>
                <span>更新日時 ---</span>
              </div>
            </div>
          </div>

          <hr className="border-slate-500 mt-2" />
        </div>

        <div className="pt-2">
          <Editor />
        </div>
      </div>
    </>
  )
}
