import Head from 'next/head'

import { Editor } from '@/components/uis/Editor'
import { IconButton } from '@/components/uis/Icon/IconButton/IconButton'
import { Tooltip } from '@/components/uis/Tooltip'

// 効いてなさそう
import 'highlight.js/styles/github-dark-dimmed.css'

// import { useRouter } from 'next/router'
// import { useEffect } from 'react'

// import { PageRepository } from '@/repository/db/page/page.repository'

// type QueryType = {
//   pageId: string
// }

// const pageRepo = new PageRepository()

export default function PageDetail() {
  // const router = useRouter()
  // const { pageId } = router.query as QueryType

  // useEffect(() => {
  //   // if (router.isReady) console.log('PageDetail', pageRepo.get(pageId))
  // }, [pageId, router])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div className="sticky top-0 bg-slate-900 z-floating -mt-4 pt-4">
          <div className="flex justify-between items-center">
            <span className="text-sm">🎉 イベント / 🛩️ イタリア旅行</span>
            <Tooltip position="bottom-left" component="シェアする">
              <IconButton icon="twitter" size="md" />
            </Tooltip>
          </div>

          <div className="px-2 py-4">
            <h1 className="w-full bg-transparent text-3xl font-extrabold mb-2">🛩️ イタリア旅行</h1>
            <div className="text-xs text-slate-300 flex gap-4">
              <div>
                <span>作成日時 2023/02/28 04:10</span>
              </div>
              <div>
                <span>更新日時 ---</span>
              </div>
            </div>
          </div>

          <hr className="border-slate-500 mt-2" />
        </div>

        <div className="pt-2">
          <Editor />
        </div>
      </div>
    </>
  )
}
